/*

Responsável por centralizar todos os dados dos quadros e itens do site.
Qualquer alteração de preço, disponibilidade ou descrição deve ser feita aqui.

Este arquivo é consumido por todas as páginas públicas do site.
*/

const itens = [
  {
    id: 1,
    categoria: "quadro",
    nome: "Zumbi e Dandara",
    descricao: "A Obra traz o amor de Zumbi e Dandara, dois heróis da história do Brasil, que lutaram para libertar os povos africanos e afrodescendentes escravizados, liderando o Quilombo dos Palmares. Zumbi e Dandara resistiram até a sua morte e são ícones da luta da liberdade do povo negro no Brasil. consulte valores para impressão Fine Art",
    tecnica: "Obra Pintada à mão",
    tamanho: "1,20 x 0.90",
    valor: 3280,
    disponivel: true,
    destaque: true,
    desconto: false,
    imagem: "/assets/itens/Zumbi e Dandara.jpg",
  },
  {
    id: 2,
    categoria: "quadro",
    nome: "Samba e Comunidade",
    descricao: "A Obra traz um casal sambando em frente da sua comunidade, destacando as origens históricas do Samba e sua identidade.",
    tecnica: "Obra Pintada à mão",
    tamanho: "1.10 x 0,90",
    valor:  2480,
    disponivel: true,
    destaque: true,
    desconto: false,
    imagem: "/assets/itens/Smba de Comunidade.jpg",
  },
  {
    id: 3,
    categoria: "quadro",
    nome: "Samba, identidade e comunidade",
    descricao: "A Obra traz a valorização da produção cultural que é produzida através da história do Brasil nas comunidades. O Samba como instrumento social de libertação e manifestação. Valorizando a identidade presente nas comunidades e as raízes do Samba.",
    tecnica: "Obra Pintada à mão",
    tamanho: "2.50 x 0.85",
    valor: 12580,
    disponivel: true,
    destaque: true,
    desconto: false,
    imagem: "/assets/itens/Samba identidade e comunidade.jpg",
  },
  {
    id: 4,
    categoria: "quadro",
    nome: "Ribeirão da Ilha",
    descricao: "Pescador e rendeira passeiam felizes pelo bairro Ribeirão da Ilha em Floripa. Ele carregando os peixes e ela a renda de Bilro, no coração muito amor e poesias. Uma Obra Cultural .",
    tecnica: "Obra Pintada à mão",
    tamanho: "2.5 x 0.90",
    valor: 5900,
    disponivel: true,
    destaque: false,
    desconto: false,
    imagem: "/assets/itens/Ribeirão da Ilha.jpg",
  },
  {
    id: 5,
    categoria: "outro",
    nome: "Nada Aqui :(",
    descricao: "NADA AQUI :(",
    tecnica: "NADA AQUI :(",
    tamanho: "NADA AQUI :(",
    valor: 0,
    disponivel: false,
    destaque: false,
    desconto: false,
    imagem: "",
  },
  {
    id: 6,
    categoria: "caneca",
    nome: "Nada Aqui :(",
    descricao: "NADA AQUI :(",
    tecnica: "NADA AQUI :(",
    tamanho: "NADA AQUI :(",
    valor: 0,
    disponivel: false,
    destaque: false,
    desconto: false,
    imagem: "",
  },
  {
    id: 7,
    categoria: "quadro",
    nome: "Rendeira Charmosa",
    descricao: "A Obra traz a delicadeza de uma rendeira tecendo uma linda renda de Bilro, patrimônio Cultural. consulte valores para impressão Fine Art",
    tecnica: "Acrílica sobre tela",
    tamanho: "0.90 x 0.70",
    valor: 2100,
    disponivel: true,
    destaque: false,
    desconto: false,
    imagem: "/assets/itens/Rendeira Charmosa 3.jpg",
  },
  {
    id: 8,
    categoria: "quadro",
    nome: "Presidente Indígena",
    descricao: "A Obra traz a valorização dos povos originários do Brasil, das mulheres indígenas e toda a sua produção intelectual e cultural para o nosso país. Reconhecer os povos originários é contudo possibilitar a visibilidade da história real do Brasil.",
    tecnica: "Acrílica sobre tela",
    tamanho: "0.85 x 1.05",
    valor: 2100,
    disponivel: true,
    destaque: true,
    desconto: false,
    imagem: "/assets/itens/Presidente Indigena.jpg",
  },
  {
    id: 9,
    categoria: "quadro",
    nome: "O menino rendeiro",
    descricao: "A Obra buscou retratar o menino Djordy e sua vovó Landa no cenário onde ela ensina a renda de Bilro para o pequeno Djordy, que na oportunidade era o menino mais jovem a fazer renda em Florianópolis.",
    tecnica: "Obra Pintada à mão",
    tamanho: "0.90 x 0.70",
    valor: 0,
    disponivel: false,
    destaque: false,
    desconto: false,
    imagem: "/assets/itens/O menino rendeiro.jpg",
  },
  {
    id: 10,
    categoria: "quadro",
    nome: "Médico Pediatra",
    descricao: "A Obra traz no cenário um menino consultando com seu médico pediatra. Num ambiente acolhedor, humanizado e cheio de carinho.",
    tecnica: "Acrílica sobre tela",
    tamanho: "1 x 1",
    valor: 2500,
    disponivel: true,
    destaque: false,
    desconto: 120,
    imagem: "/assets/itens/O Médico.jpg",
  },
  {
    id: 11,
    categoria: "quadro",
    nome: "Nossa Senhora Desatadora dos Nós",
    descricao: "A Obra traz a Nossa Senhora Desatadora dos Nós opera na intercessão de Maria para resolver os nós da vida cotidiana, espiritual e familiar.",
    tecnica: "Acrílica sobre tela",
    tamanho: "1.80 x 0.85",
    valor: 3000,
    disponivel: true,
    destaque: false,
    desconto: 110,
    imagem: "/assets/sobremim.jpeg",
  },
  {
    id: 12,
    categoria: "quadro",
    nome: "Nina Silva",
    descricao: "A Obra traz O Movimento Black Money. Inspirado na empresária Nina Silva, uma das idealizadoras do movimento Black Money no Brasil. O empoderamento econômico das pessoas pretas.",
    tecnica: "Obra de Arte Pintada a mão",
    tamanho: "0.90 x 0.70",
    valor: 3150,
    disponivel: true,
    destaque: false,
    desconto: 300,
    imagem: "/assets/itens/Nina Silva Diagonal.jpg",
  },
  {
    id: 13,
    categoria: "quadro",
    nome: "Mulheres Negras na Política",
    descricao: "A Obra se trata sobre a importância da representatividade das mulheres negras na política.",
    tecnica: "Obra de Arte Pintada à Mão",
    tamanho: "90 x 0.70",
    valor: 2180,
    disponivel: true,
    destaque: false,
    desconto: false,
    imagem: "/assets/itens/Mulheres Negras na Politicaa.jpg",
  },
  {
    id: 14,
    categoria: "quadro",
    nome: "Santa Paulina",
    descricao: "Madre Paulina (Amábile Lúcia Visintainer, 1865-1942) foi uma religiosa ítalo-brasileira, a primeira santa canonizada do Brasil, residiu na cidade de Nova Trento SC, onde foi construído um lindo santuário, que é visitado por muitos fiéis.",
    tecnica: "Obra de Arte Pintada à Mão",
    tamanho: "Erro: não tenho essa informação",
    valor: 2180,
    disponivel: true,
    destaque: true,
    desconto: false,
    imagem: "/assets/itens/Madre Paulina.jpg",
  },
  {
    id: 15,
    categoria: "quadro",
    nome: "Dra Pâmela",
    descricao: "Uma encomenda personalizada para Farmacêutica Esteta, querida Dra. Pâmela.",
    tecnica: "Obra de Arte Pintada à Mão",
    tamanho: "1.40 x 0.85",
    valor: 0,
    disponivel: false,
    destaque: false,
    desconto: false,
    imagem: "/assets/itens/Dra PamelaD.jpg",
  },
  {
    id: 16,
    categoria: "quadro",
    nome: "Djamila Ribeiro",
    descricao: "A Obra trabalha a temática da educação antirracista. A importância de leituras que abordam a temática no combate ao racismo e o letramento racial, que diz respeito a toda a sociedade.",
    tecnica: "Acrílica sobre tela",
    tamanho: "1.45 x 0.85",
    valor: 3220,
    disponivel: true,
    destaque: true,
    desconto: false,
    imagem: "/assets/itens/Djamila Ribeiro.jpg",
  },
  {
    id: 17,
    categoria: "quadro",
    nome: "Corre que lá vem a Bernunça",
    descricao: "Obra compõe um cenário divertido onde as crianças correm assustadas da Bernunça. Uma brincadeira que faz parte da cultura do Boi-de-mamão.",
    tecnica: "Obra de Arte Pintada à Mão",
    tamanho: "1 x 0.80",
    valor: 3180,
    disponivel: true,
    destaque: false,
    desconto: false,
    imagem: "/assets/itens/Corre que lá vem a Bernunça III.jpg",
  },
  {
    id: 18,
    categoria: "quadro",
    nome: "O Carnaval",
    descricao: "A Obra traz a alegria do carnaval, valorizando a história do povo negro no Brasil através das manifestações culturais. A produção cultural e social promovida pelas escolas de Samba, como ferramenta de transformação social, identidade e história.",
    tecnica: "Obra de Arte Pintada à Mão",
    tamanho: "1,80 x 0.85",
    valor: 3150,
    disponivel: true,
    destaque: false,
    desconto: false,
    imagem: "/assets/itens/Carnaval_.jpg",
  },
  {
    id: 19,
    categoria: "quadro",
    nome: "As Amigas",
    descricao: "A obra traz um encontro de amigas que compartilham risadas, um boa conversa e muita alegria.",
    tecnica: "Acrílica sobre tela",
    tamanho: "1,35 x 0.85",
    valor: 2580,
    disponivel: true,
    destaque: false,
    desconto: false,
    imagem: "/assets/itens/as amigas sem md.jpg",
  },
  {
    id: 20,
    categoria: "quadro",
    nome: "Ancestralidade a Nossa Força",
    descricao: "a Obra busca retratar aspectos históricos sobre a ancestralidade dos povos  afrodescendentes no Brasil. As mulheres africanas que foram escravizadas e a sua luta para vencer todos os impactos do processo de escravização no país. Desafios e conquistas vivenciados por gerações. A Miscigenação, as mudanças culturais e os desafios para o acesso a educação do povo negro.",
    tecnica: "Obra de Arte Pintada à Mão",
    tamanho: "1,85 x 0.85",
    valor: 4500,
    disponivel: true,
    destaque: false,
    desconto: false,
    imagem: "/assets/itens/Ancestralidade a nossa força.jpg",
  },
  {
    id: 21,
    categoria: "quadro",
    nome: "Amor em Floripa",
    descricao: "Uma obra que fala de amor.",
    tecnica: "Obra de Arte Pintada à Mão",
    tamanho: "1.80 x 0.85",
    valor: 3280,
    disponivel: true,
    destaque: true,
    desconto: false,
    imagem: "/assets/itens/Amor em Floripa.jpg",
  },
  {
    id: 22,
    categoria: "quadro",
    nome: "As Amigas II",
    descricao: "A obra traz um encontro de amigas que compartilham risadas, um boa conversa e muita alegria.",
    tecnica: "Acrílica sobre tela",
    tamanho: "1.70 x 0.85",
    valor: 3500,
    disponivel: true,
    destaque: false,
    desconto: 250,
    imagem: "/assets/itens/amigas II_.jpg",
  },
  {
    id: 23,
    categoria: "quadro",
    nome: "Amanda, minha Filha",
    descricao: "A Obra se trata de um presente que a Artista pintou para a filha Amanda, quando estava grávida da sua netinha Sara.",
    tecnica: "Obra de Arte Pintada à Mão",
    tamanho: "0.70 x 0.50",
    valor: 0,
    disponivel: false,
    destaque: false,
    desconto: false,
    imagem: "/assets/itens/Amanda, minha filha_ Vida_.jpg",
  },
  {
    id: 24,
    categoria: "quadro",
    nome: "A luta antirracista é de todos",
    descricao: "A Obra busca despertar reflexões sobre a luta antirracista e educação antirracista.",
    tecnica: "Obra de Arte Pintada à Mão",
    tamanho: "1.35 x 0.85",
    valor: 3230,
    disponivel: true,
    destaque: false,
    desconto: false,
    imagem: "/assets/itens/A luta antirracista é de todo_s.jpg",
  },
  {
    id: 25,
    categoria: "quadro",
    nome: "A Chef",
    descricao: "A Obra traz uma chef de cozinha preparando pratos da culinária brasileira.",
    tecnica: "Obra de Arte Pintada à Mão",
    tamanho: "0.90 x 0.70",
    valor: 1580,
    disponivel: true,
    destaque: false,
    desconto: false,
    imagem: "/assets/itens/A luta antirracista é de todo_s.jpg",
  },
  {
    id: 26,
    categoria: "quadro",
    nome: "Mãe Preta Solo",
    descricao: "A Obra traz uma mulher Preta com seus filhos, num cenário onde leva as crianças para a escola e está indo trabalhar. No Brasil estatisticamente são em torno de  61% a 90% de mulheres negras que são mães solo.",
    tecnica: "Acrílica sobre tela",
    tamanho: "1.55 x 0.85",
    valor: 3580,
    disponivel: true,
    destaque: false,
    desconto: false,
    imagem: "/assets/itens/_Mãe Preta Solo.jpg",
  },
];
